/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PuzzleGame;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author viet1
 */
public class PuzzleGame extends javax.swing.JFrame {

    /**
     * Creates new form PuzzleGame
     */
    public PuzzleGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlbNumberOfClicks = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPrie = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        resText = new javax.swing.JLabel();
        resText1 = new javax.swing.JLabel();
        titleCheck = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnReplay = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        btnBeFS = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(820, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(197, 227, 209));

        btn1.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setText("1");
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn2.setForeground(new java.awt.Color(51, 51, 51));
        btn2.setText("2");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn3.setForeground(new java.awt.Color(51, 51, 51));
        btn3.setText("3");
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn4.setForeground(new java.awt.Color(51, 51, 51));
        btn4.setText("4");
        btn4.setEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn5.setForeground(new java.awt.Color(51, 51, 51));
        btn5.setText("5");
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn6.setForeground(new java.awt.Color(51, 51, 51));
        btn6.setText("6");
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn7.setForeground(new java.awt.Color(51, 51, 51));
        btn7.setText("7");
        btn7.setEnabled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn8.setForeground(new java.awt.Color(51, 51, 51));
        btn8.setText("8");
        btn8.setEnabled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(203, 218, 196));

        jButton2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 105, 124));
        jButton2.setText("1");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 105, 124));
        jButton3.setText("2");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton4.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 105, 124));
        jButton4.setText("3");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 105, 124));
        jButton5.setText("4");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton6.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 105, 124));
        jButton6.setText("5");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton7.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 105, 124));
        jButton7.setText("6");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton9.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 105, 124));
        jButton9.setText("7");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton10.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 105, 124));
        jButton10.setText("8");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setIconTextGap(0);
        jButton10.setMargin(new java.awt.Insets(4, 14, 3, 14));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 240, -1));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setForeground(new java.awt.Color(203, 218, 196));

        jlbNumberOfClicks.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jlbNumberOfClicks.setForeground(new java.awt.Color(0, 102, 204));
        jlbNumberOfClicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNumberOfClicks.setText("0");
        jlbNumberOfClicks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText(" Steps:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPrie.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnPrie.setText("▲");
        btnPrie.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        btnPrie.setEnabled(false);
        btnPrie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrie.setMinimumSize(new java.awt.Dimension(19, 31));
        btnPrie.setName(""); // NOI18N
        btnPrie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrieActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnNext.setText("▼");
        btnNext.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        btnNext.setEnabled(false);
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btnNext.setMaximumSize(new java.awt.Dimension(19, 19));
        btnNext.setMinimumSize(new java.awt.Dimension(19, 31));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jlbNumberOfClicks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrie, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbNumberOfClicks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 240, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(203, 218, 196));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 240, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(203, 218, 196));

        resText.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        resText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        resText1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        resText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resText1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        titleCheck.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        titleCheck.setText("   Number of vertices checked");
        titleCheck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resText1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleCheck)
                .addGap(5, 5, 5)
                .addComponent(resText1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 240, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(203, 218, 196));

        btnReplay.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        btnReplay.setText("Replay");
        btnReplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplayActionPerformed(evt);
            }
        });

        btnBFS.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        btnBFS.setText("BFS-Sol");
        btnBFS.setActionCommand("BFS\nSolution");
        btnBFS.setEnabled(false);
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });

        btnBeFS.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        btnBeFS.setText("AStart");
        btnBeFS.setEnabled(false);
        btnBeFS.setMargin(new java.awt.Insets(2, 10, 3, 10));
        btnBeFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeFSActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReplay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBeFS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeFS, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 480, 100));

        btnStart.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnStart.setText("Start");
        btnStart.setEnabled(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 80, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 10, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /****************************************************************************/
    int Counter; // Tạo biến dùng để đếm số bước đi
    /****************************************************************************/
    // Tạo hàm kiểm tra xem hai nút liền kề có nút trống hay không.
    // Nếu có thì thực hiện hoán đổi giá trị của hai nút này.
    void EmptySpotChecker(JButton btn1, JButton btn2){
        if(btn2.getText().equals("")){ // Thực hiện kiểm tra xem nút hàng xóm của nút đang xét có rỗng không
            btn2.setText(btn1.getText()); // Nếu có, thực hiện thiết lập giá trị nút đang xét cho nút hàng xóm
            btn1.setText(""); // Thiết lập giá trị cho nút đang xét bằng rỗng.
            checkWin(); // Mỗi lần di chuyển kiểm tra xem trạng thái đã là trạng thái đích hay chưa
            // Chỉ tăng số lần di chuyển khi di chuyển là hợp lệ
        }
    }
    /****************************************************************************/
    // ================= Demo bằng mảng hai chiều ================== //
    /*
    | 1 | 2 | 3 |
    | 4 | 5 | 6 |
    | 7 | 8 | 9 |
    
    Có thể thấy:
    1 có thể đi đến 2 hoặc 4 nếu 2 hoặc 4 là rỗng
    2 có thể đi đến 1 hoặc 3 hoặc 5
    3 có thể đi đến 2 hoặc 6
    4 có thể đi đến 1 hoặc 5 hoặc 7
    5 có thể đi đến 2 hoặc 4 hoặc 6 hoặc 8
    6 có thể đi đến 3 hoặc 5 hoặc 9
    7 có thể đi đến hoặc 4 hoặc 8
    8 có thể đi đến hoặc 5 hoặc 7 hoặc 9
    9 có thể đi đến hoặc 8 hoặc 6
    */
    /****************************************************************************/
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn1, btn2);
        EmptySpotChecker(btn1, btn4);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn3, btn2);
        EmptySpotChecker(btn3, btn6);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn2, btn1);
        EmptySpotChecker(btn2, btn3);
        EmptySpotChecker(btn2, btn5);

    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn4, btn1);
        EmptySpotChecker(btn4, btn5);
        EmptySpotChecker(btn4, btn7);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn5, btn2);
        EmptySpotChecker(btn5, btn4);
        EmptySpotChecker(btn5, btn6);
        EmptySpotChecker(btn5, btn8);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn6, btn3);
        EmptySpotChecker(btn6, btn5);
        EmptySpotChecker(btn6, btn9);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn7, btn4);
        EmptySpotChecker(btn7, btn8);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        EmptySpotChecker(btn8, btn5);
        EmptySpotChecker(btn8, btn7);
        EmptySpotChecker(btn8, btn9);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        EmptySpotChecker(btn9, btn8);
        EmptySpotChecker(btn9, btn6);
    }  
    /****************************************************************************/ 
    // ===================== Sinh mảng ngẫu nhiên ============================= //
    /****************************************************************************/
    public void Shuffle(){ // Tạo hàm xáo trộn ngẫu nhiên
        // Collections trong java hỗ trợ trộn mảng ngẫu nhiên (tham khảo trên JavatPoint)
        Integer[] bNum = {1, 2, 3, 4, 5, 6, 7, 8, 9}; // Tạo mảng gốc gồm có 8 phần tử tương ứng với 8 chữ số
        // Việc khai báo mảng với lớp Integer sẽ linh hoạt hơn so với kiểu dữ liệu nguyên thủy int
        // Thực hiện chuyển từ mảng sang dạng list để xáo trộn mảng
        var list = Arrays.asList(bNum);
        // Thực hiện xáo trộn mảng với Collections
        Collections.shuffle(list);
        // Convert lại list sang mảng và lưu vào bNum;
        list.toArray(bNum);
        // Thiết lập các giá trị ngẫu nhiên cho các nút theo giá trị trong mảng
        if(bNum[0] == 9)
            btn1.setText("");
        else
            btn1.setText(bNum[0].toString());
        if(bNum[1] == 9)
            btn2.setText("");
        else
            btn2.setText(bNum[1].toString());
        if(bNum[2] == 9)
            btn3.setText("");
        else
            btn3.setText(bNum[2].toString());
        if(bNum[3] == 9)
            btn4.setText("");
        else
            btn4.setText(bNum[3].toString());
        if(bNum[4] == 9)
            btn5.setText("");
        else
            btn5.setText(bNum[4].toString());
        if(bNum[5] == 9)
            btn6.setText("");
        else
            btn6.setText(bNum[5].toString());
        if(bNum[6] == 9)
            btn7.setText("");
        else
            btn7.setText(bNum[6].toString());
        if(bNum[7] == 9)
            btn8.setText("");
        else
            btn8.setText(bNum[7].toString());
        if(bNum[8] == 9)
            btn9.setText("");
        else
            btn9.setText(bNum[8].toString());
    }
    /****************************************************************************/
    // =========================== Kiểm tra win ================================//
    /****************************************************************************/
    public void checkWin(){
        String b1 = btn1.getText();
        String b2 = btn2.getText();
        String b3 = btn3.getText();
        String b4 = btn4.getText();
        String b5 = btn5.getText();
        String b6 = btn6.getText();
        String b7 = btn7.getText();
        String b8 = btn8.getText();
        // Dùng hàm if kiểm tra xem các số đã đúng vị trí hay chưa ?
        if(b1.equals("1") && b2.equals("2") && b3.equals("3") && b4.equals("4") && 
                b5.equals("5") && b6.equals("6") && b7.equals("7") && b8.equals("8")){
            // Nếu đúng thì hiển thị lê hộp thông báo chiến thắng
            JOptionPane.showMessageDialog(this, "You Win!", "Congratulation!", JOptionPane.INFORMATION_MESSAGE);
            btnReplay.setText("New Game"); // Thay đổi tên nút replay thành new game
        }
        
        ++ Counter; // Nếu chưa win thì tăng lần di chuyển lên 1
        
        jlbNumberOfClicks.setText(Integer.toString(Counter)); // Hiển thị số lần di chuyển ra màn hình
    }
    /****************************************************************************/
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    // ===================== Sự kiện nút replay ============================= \\
    private void btnReplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplayActionPerformed
        // TODO add your handling code here:
        resText.setText("");
        titleCheck.setVisible(false);
        resText1.setText("");
        solution = new ArrayList<State>();
        tracing = new ArrayList<State>();
        steps = 0;
        btnStart.setEnabled(true);
        if(btnReplay.getText().equals("New Game")){ // Kiểm tra nếu như đang là new game thì đổi lại thành replay
            btnReplay.setText("Replay");
        }
        Shuffle(); // Gọi hàm trộn mảng để tạo ra trò chơi mới
        Counter = 0; // Thiết lập lại bộ đếm bước đi bằng 0
        jlbNumberOfClicks.setText("0"); // Thiết lập lại hiển thị bước đi bằng 0.
        btnBeFS.setEnabled(false);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btnPrie.setEnabled(false);
        btnNext.setEnabled(false);
    }//GEN-LAST:event_btnReplayActionPerformed
    /****************************************************************************/
    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnBeFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeFSActionPerformed
        // TODO add your handling code here:
        solution.clear();
        tracing.clear();
        steps = 0;
        Main mn = new Main();
        Integer[] start = new Integer[9];
        String b1 = btn1.getText();
        String b2 = btn2.getText();
        String b3 = btn3.getText();
        String b4 = btn4.getText();
        String b5 = btn5.getText();
        String b6 = btn6.getText();
        String b7 = btn7.getText();
        String b8 = btn8.getText();
        String b9 = btn9.getText();
        if(b1.equals(""))
            b1 = "9";
        if(b2.equals(""))
            b2 = "9";
        if(b3.equals(""))
            b3 = "9";
        if(b4.equals(""))
            b4 = "9";
        if(b5.equals(""))
            b5 = "9";
        if(b6.equals(""))
            b6 = "9";
        if(b7.equals(""))
            b7 = "9";
        if(b8.equals(""))
            b8 = "9";
        if(b9.equals(""))
            b9 = "9";
        start[0] = Integer.valueOf(b1);
        start[1] = Integer.valueOf(b2);
        start[2] = Integer.valueOf(b3);
        start[3] = Integer.valueOf(b4);
        start[4] = Integer.valueOf(b5);
        start[5] = Integer.valueOf(b6);
        start[6] = Integer.valueOf(b7);
        start[7] = Integer.valueOf(b8);
        start[8] = Integer.valueOf(b9);
        
        for(var i : tracing)
            i.print();
        long time1 = 0, time2 = 0;
        try {
            time1 = new Date().getTime();
            mn.solution(start);
            time2 = new Date().getTime();
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(PuzzleGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        solution = mn.temp;
        resText.setText(Long.toString(time2 - time1) + " miliseconds");
        titleCheck.setVisible(true);
        resText1.setText(Integer.toString(mn.saw));
        
        
        int i = 0;
        while(i < solution.size()){
            tracing.add(solution.get(i));
            ++ i;
        }
        jlbNumberOfClicks.setText(Integer.toString(1) + " / " + Integer.toString(tracing.size()));
        btnPrie.setEnabled(true);
        btnNext.setEnabled(true);
        btnBeFS.setEnabled(false);
    }//GEN-LAST:event_btnBeFSActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        btnReplay.setText("New Game");
        titleCheck.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    public List<State> solution = new ArrayList<State>();;
    public List<State> tracing = new ArrayList<State>();;
    public int steps = 0;
    
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btnBeFS.setEnabled(true);
        btnStart.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPrieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrieActionPerformed
        // TODO add your handling code here:
        if(steps < 1)
            steps = 1;
        if(steps > 0){
            Integer[] bNum = Arrays.copyOfRange(tracing.get(steps - 1).data, 0, 9);
            
            if(bNum[0] == 9)
                btn1.setText("");
            else
                btn1.setText(bNum[0].toString());
            if(bNum[1] == 9)
                btn2.setText("");
            else
                btn2.setText(bNum[1].toString());
            if(bNum[2] == 9)
                btn3.setText("");
            else
                btn3.setText(bNum[2].toString());
            if(bNum[3] == 9)
                btn4.setText("");
            else
                btn4.setText(bNum[3].toString());
            if(bNum[4] == 9)
                btn5.setText("");
            else
                btn5.setText(bNum[4].toString());
            if(bNum[5] == 9)
                btn6.setText("");
            else
                btn6.setText(bNum[5].toString());
            if(bNum[6] == 9)
                btn7.setText("");
            else
                btn7.setText(bNum[6].toString());
            if(bNum[7] == 9)
                btn8.setText("");
            else
                btn8.setText(bNum[7].toString());
            if(bNum[8] == 9)
                btn9.setText("");
            else
                btn9.setText(bNum[8].toString());
        }
        --steps;
        jlbNumberOfClicks.setText(Integer.toString(steps + 1) + " / " + Integer.toString(tracing.size()));
        System.out.println(steps);
//        tracing.get(0).print();
    }//GEN-LAST:event_btnPrieActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(steps > tracing.size() - 2)
            steps = tracing.size() - 2;
        if(steps < solution.size() - 1 ){
            Integer[] bNum = Arrays.copyOfRange(tracing.get(steps + 1).data, 0, 9);
            
            if(bNum[0] == 9)
                btn1.setText("");
            else
                btn1.setText(bNum[0].toString());
            if(bNum[1] == 9)
                btn2.setText("");
            else
                btn2.setText(bNum[1].toString());
            if(bNum[2] == 9)
                btn3.setText("");
            else
                btn3.setText(bNum[2].toString());
            if(bNum[3] == 9)
                btn4.setText("");
            else
                btn4.setText(bNum[3].toString());
            if(bNum[4] == 9)
                btn5.setText("");
            else
                btn5.setText(bNum[4].toString());
            if(bNum[5] == 9)
                btn6.setText("");
            else
                btn6.setText(bNum[5].toString());
            if(bNum[6] == 9)
                btn7.setText("");
            else
                btn7.setText(bNum[6].toString());
            if(bNum[7] == 9)
                btn8.setText("");
            else
                btn8.setText(bNum[7].toString());
            if(bNum[8] == 9)
                btn9.setText("");
            else
                btn9.setText(bNum[8].toString());
        }
        ++ steps;
        jlbNumberOfClicks.setText(Integer.toString(steps + 1) + " / " + Integer.toString(tracing.size()));
        System.out.println(steps);
    }//GEN-LAST:event_btnNextActionPerformed

    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame, "Do you want to exit?", "Exit", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }                                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzleGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnBeFS;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrie;
    private javax.swing.JButton btnReplay;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlbNumberOfClicks;
    private javax.swing.JLabel resText;
    private javax.swing.JLabel resText1;
    private javax.swing.JLabel titleCheck;
    // End of variables declaration//GEN-END:variables
}
